'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { siteMetrics } from '@/content/metrics';
import { SectionHeader } from '@/components/ui/SectionHeader';

export function NumbersSection() {
  return (
    <section className="py-24 md:py-36 border-t border-white/5 relative bg-[#09090B]">
      <div className="max-w-7xl mx-auto px-6 md:px-12">
        <SectionHeader
          label="TRACTION & REACH"
          title="SOME NUMBERS I LIKE."
          subtitle="Real volume generated by real African businesses. And one metric that explains my search history."
          badgeColor="#B8FF3D"
        />

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {siteMetrics.map((stat, i) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-40px' }}
              transition={{ duration: 0.5, delay: i * 0.1 }}
              className="p-8 rounded-3xl bg-[#111116] border border-white/10 hover:border-white/20 transition-all relative overflow-hidden group shadow-lg"
            >
              {/* Glow Accent */}
              <div className="absolute top-0 right-0 w-32 h-32 bg-[#315BFF]/10 rounded-full blur-2xl pointer-events-none group-hover:bg-[#315BFF]/20 transition-all" />

              <div className="relative z-10">
                <span className="text-4xl sm:text-5xl lg:text-6xl font-black font-mono text-[#F5F3EE] tracking-tight block mb-3 group-hover:text-[#315BFF] transition-colors">
                  {stat.value}
                </span>

                <h3 className="font-mono text-xs uppercase tracking-widest text-[#B8FF3D] font-bold mb-2">
                  {stat.label}
                </h3>

                {stat.subtext && (
                  <p className="text-xs text-[#888899] font-light leading-relaxed">
                    {stat.subtext}
                  </p>
                )}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
